In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)

In [2]:
x1 = rng.integers(10, size=6) # one dimensional array
x2 = rng.integers(10, size=(3,4)) # two dimensional array
x3 = rng.integers(10, size=(3,4,5)) # three dimensional array

In [3]:
print(x1)
print(x2)
print(x3)

[9 4 0 3 8 6]
[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
[[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]


In [4]:
x3[2,3,2:4]

array([7, 4])

In [5]:
grid = np.arange(1, 10).reshape(3,3)

In [6]:
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
import pandas as pd

In [8]:
import pandas as pd
df_x = pd.DataFrame({
    'First Name': ['Fahim','Faisal','Abdur'],
    'Last Name': ['Faisal', 'Rahman', 'Rahman'],
    'Class ID': [10, 20, 30],
    'Section': ['A', 'B', 'C'] 
}, index = [1, 2, 3])

In [9]:
df_x

First Name Last Name  Class ID Section
1      Fahim    Faisal        10       A
2     Faisal    Rahman        20       B
3      Abdur    Rahman        30       C

In [10]:
df_y = pd.DataFrame({
    'Test Score': [100, 50, 30],
    'Class ID': [10, 20, 30]
}, index=['a', 'b','c'])

In [11]:
df_y

Test Score  Class ID
a         100        10
b          50        20
c          30        30

In [12]:
df_x = df_x.merge(df_y, how='left', left_on='Class ID', right_on='Class ID')

In [13]:
df_x

First Name Last Name  Class ID Section  Test Score
0      Fahim    Faisal        10       A         100
1     Faisal    Rahman        20       B          50
2      Abdur    Rahman        30       C          30

In [14]:
x = np.array([1,2,3])
y = np.array([3,4,5])
np.concatenate([x,y])

array([1, 2, 3, 3, 4, 5])

In [15]:
df_x['Full Name'] = df_x['First Name'] + " " + df_x['Last Name']

In [16]:
df_x

First Name Last Name  Class ID Section  Test Score      Full Name
0      Fahim    Faisal        10       A         100   Fahim Faisal
1     Faisal    Rahman        20       B          50  Faisal Rahman
2      Abdur    Rahman        30       C          30   Abdur Rahman

In [17]:
df_x.drop(columns=['First Name', 'Last Name'])

Class ID Section  Test Score      Full Name
0        10       A         100   Fahim Faisal
1        20       B          50  Faisal Rahman
2        30       C          30   Abdur Rahman

In [18]:
df_x_column_to_move = df_x.pop('Full Name')

In [19]:
df_x.insert(0, 'Full Name', df_x_column_to_move)

In [20]:
df_x

Full Name First Name Last Name  Class ID Section  Test Score
0   Fahim Faisal      Fahim    Faisal        10       A         100
1  Faisal Rahman     Faisal    Rahman        20       B          50
2   Abdur Rahman      Abdur    Rahman        30       C          30

In [21]:
df_x = df_x.drop(columns=['First Name', 'Last Name'])

In [22]:
df_x

Full Name  Class ID Section  Test Score
0   Fahim Faisal        10       A         100
1  Faisal Rahman        20       B          50
2   Abdur Rahman        30       C          30

In [23]:
df_x[['First Name', 'Last Name']] = df_x['Full Name'].str.split(' ', expand=True)

In [24]:
df_x

Full Name  Class ID Section  Test Score First Name Last Name
0   Fahim Faisal        10       A         100      Fahim    Faisal
1  Faisal Rahman        20       B          50     Faisal    Rahman
2   Abdur Rahman        30       C          30      Abdur    Rahman

In [25]:
df_x = df_x.drop(columns=['Full Name'])

In [26]:
df_x_move_to_new_columns = df_x.pop('First Name')

In [30]:
df_x = df_x.insert(0, 'First Name', df_x_move_to_new_columns)


In [32]:
print(df_x)

None


In [33]:
import pandas as pd

df_x = pd.DataFrame({
'First Name': ['Fahim', 'Faisal', 'Abdur'],
'Last Name': ['Faisal', 'Rahman', 'Rahman'],
'Class ID': [10, 20, 30],
'Section' : ['A', 'B', 'C']
}, index = [1,2,3])

    

In [34]:
df_x

First Name Last Name  Class ID Section
1      Fahim    Faisal        10       A
2     Faisal    Rahman        20       B
3      Abdur    Rahman        30       C

In [35]:
df_y = pd.DataFrame({
    'Test Score': [100, 50, 20],
    'Class ID': [10, 20, 30],}, index = [1,2,3])

In [36]:
df_y

Test Score  Class ID
1         100        10
2          50        20
3          20        30

In [38]:
df_x =df_x.merge(df_y, how='left', left_on='Class ID', right_on='Class ID')

In [39]:
df_x

First Name Last Name  Class ID Section  Test Score
0      Fahim    Faisal        10       A         100
1     Faisal    Rahman        20       B          50
2      Abdur    Rahman        30       C          20

In [40]:
df_x['Full Name'] = df_x['First Name'] + " " + df_x['Last Name']

In [41]:
df_x

First Name Last Name  Class ID Section  Test Score      Full Name
0      Fahim    Faisal        10       A         100   Fahim Faisal
1     Faisal    Rahman        20       B          50  Faisal Rahman
2      Abdur    Rahman        30       C          20   Abdur Rahman

In [43]:
df_x = df_x.drop(columns=['First Name', 'Last Name'])

In [44]:
df_x

Class ID Section  Test Score      Full Name
0        10       A         100   Fahim Faisal
1        20       B          50  Faisal Rahman
2        30       C          20   Abdur Rahman

In [52]:
df_x_column_to_move = df_x.pop('Full Name')

In [53]:
df_x.insert(0, 'Full Name', df_x_column_to_move)

In [54]:
df_x

Full Name  Class ID Section  Test Score
0   Fahim Faisal        10       A         100
1  Faisal Rahman        20       B          50
2   Abdur Rahman        30       C          20